import { categories, materials } from "../src/lib/data";

const TENANT_ID = "00000000-0000-0000-0000-000000000001";
const TENANT_NAME = "三信産業";
const TENANT_SLUG = "sanshin";

function sqlString(s: string | null | undefined): string {
  if (s === null || s === undefined) return "null";
  return "'" + s.replace(/'/g, "''") + "'";
}

function sqlJsonb(obj: Record<string, string> | null | undefined): string {
  if (!obj || Object.keys(obj).length === 0) return "'{}'::jsonb";
  return sqlString(JSON.stringify(obj)) + "::jsonb";
}

const lines: string[] = [];

lines.push("-- ============================================================");
lines.push("-- Phase 1 schema + seed (auto-generated by scripts/generate-seed.ts)");
lines.push("-- ============================================================");
lines.push("");
lines.push("-- ============================================================");
lines.push("-- Schema");
lines.push("-- ============================================================");
lines.push("");
lines.push(`drop table if exists audit_logs cascade;`);
lines.push(`drop table if exists email_logs cascade;`);
lines.push(`drop table if exists order_items cascade;`);
lines.push(`drop table if exists orders cascade;`);
lines.push(`drop table if exists material_images cascade;`);
lines.push(`drop table if exists images cascade;`);
lines.push(`drop table if exists material_variants cascade;`);
lines.push(`drop table if exists materials cascade;`);
lines.push(`drop table if exists categories cascade;`);
lines.push(`drop table if exists tenants cascade;`);
lines.push("");

lines.push(`create table tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);`);
lines.push("");

lines.push(`create table categories (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  name text not null,
  slug text not null,
  image_url text,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (tenant_id, slug)
);
create index idx_categories_tenant on categories(tenant_id);`);
lines.push("");

lines.push(`create table materials (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  category_id uuid not null references categories(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  spec jsonb,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, slug)
);
create index idx_materials_tenant on materials(tenant_id);
create index idx_materials_category on materials(category_id);
create index idx_materials_active on materials(is_active) where is_active = true;`);
lines.push("");

lines.push(`create table material_variants (
  id uuid primary key default gen_random_uuid(),
  material_id uuid not null references materials(id) on delete cascade,
  name text not null,
  spec jsonb,
  sku text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create index idx_variants_material on material_variants(material_id);`);
lines.push("");

lines.push(`create table images (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  url text not null,
  caption text,
  source text,
  created_at timestamptz not null default now(),
  unique (tenant_id, url)
);
create index idx_images_tenant on images(tenant_id);`);
lines.push("");

lines.push(`create table material_images (
  material_id uuid not null references materials(id) on delete cascade,
  image_id uuid not null references images(id) on delete cascade,
  sort_order int not null default 0,
  is_primary boolean not null default false,
  primary key (material_id, image_id)
);
create index idx_material_images_image on material_images(image_id);`);
lines.push("");

lines.push(`create table orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  order_number text not null,
  company_name text not null,
  contact_name text not null,
  phone text,
  email text,
  note text,
  status text not null default 'pending',
  approved_at timestamptz,
  approved_by text,
  reject_reason text,
  rejected_at timestamptz,
  shipped_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (tenant_id, order_number)
);
create index idx_orders_tenant on orders(tenant_id);
create index idx_orders_status on orders(status);`);
lines.push("");

lines.push(`create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  material_id uuid not null references materials(id),
  variant_id uuid references material_variants(id),
  material_name text not null,
  variant_name text,
  quantity int not null,
  approved_quantity int,
  created_at timestamptz not null default now()
);
create index idx_order_items_order on order_items(order_id);`);
lines.push("");

lines.push(`create table email_logs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  order_id uuid references orders(id) on delete set null,
  to_address text not null,
  subject text not null,
  body text,
  kind text not null,
  status text not null default 'sent',
  error text,
  sent_at timestamptz not null default now()
);
create index idx_email_logs_order on email_logs(order_id);
create index idx_email_logs_tenant on email_logs(tenant_id);`);
lines.push("");

lines.push(`create table audit_logs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references tenants(id),
  actor text,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  diff jsonb,
  created_at timestamptz not null default now()
);
create index idx_audit_logs_tenant on audit_logs(tenant_id);
create index idx_audit_logs_entity on audit_logs(entity_type, entity_id);`);
lines.push("");

lines.push("-- ============================================================");
lines.push("-- Seed");
lines.push("-- ============================================================");
lines.push("");

lines.push(`insert into tenants (id, name, slug) values
  ('${TENANT_ID}', ${sqlString(TENANT_NAME)}, ${sqlString(TENANT_SLUG)});`);
lines.push("");

lines.push("-- categories");
const categoryValues = categories.map(c =>
  `  ('${TENANT_ID}', ${sqlString(c.name)}, ${sqlString(c.slug)}, ${sqlString(c.image_url)}, ${c.sort_order})`
).join(",\n");
lines.push(`insert into categories (tenant_id, name, slug, image_url, sort_order) values\n${categoryValues};`);
lines.push("");

lines.push("-- materials");
const materialValues = materials.map(m => {
  const catSlug = categories.find(c => c.id === m.category_id)?.slug;
  return `  ('${TENANT_ID}', (select id from categories where tenant_id='${TENANT_ID}' and slug=${sqlString(catSlug!)}), ${sqlString(m.name)}, ${sqlString(m.slug)}, ${sqlString(m.description)}, ${sqlJsonb(m.spec)}, ${m.sort_order}, ${m.is_active})`;
}).join(",\n");
lines.push(`insert into materials (tenant_id, category_id, name, slug, description, spec, sort_order, is_active) values\n${materialValues};`);
lines.push("");

lines.push("-- images (unique URLs collected from materials' image_url + catalog_pages)");
const urlSet = new Set<string>();
for (const m of materials) {
  if (m.image_url) urlSet.add(m.image_url);
  for (const p of (m.catalog_pages || [])) urlSet.add(p);
}
const urls = Array.from(urlSet).sort();
const imageValues = urls.map(u => `  ('${TENANT_ID}', ${sqlString(u)})`).join(",\n");
lines.push(`insert into images (tenant_id, url) values\n${imageValues};`);
lines.push("");

lines.push("-- material_images (M:N)");
type MILink = { slug: string; url: string; sort_order: number; is_primary: boolean };
const miLinks: MILink[] = [];
for (const m of materials) {
  const seen = new Set<string>();
  let order = 0;
  if (m.image_url) {
    miLinks.push({ slug: m.slug, url: m.image_url, sort_order: order++, is_primary: true });
    seen.add(m.image_url);
  }
  for (const p of (m.catalog_pages || [])) {
    if (seen.has(p)) continue;
    miLinks.push({ slug: m.slug, url: p, sort_order: order++, is_primary: false });
    seen.add(p);
  }
}
const miValues = miLinks.map(l =>
  `  (${sqlString(l.slug)}, ${sqlString(l.url)}, ${l.sort_order}, ${l.is_primary})`
).join(",\n");
lines.push(`insert into material_images (material_id, image_id, sort_order, is_primary)
select m.id, i.id, v.sort_order, v.is_primary
from (values
${miValues}
) as v(material_slug, image_url, sort_order, is_primary)
join materials m on m.tenant_id='${TENANT_ID}' and m.slug = v.material_slug
join images i on i.tenant_id='${TENANT_ID}' and i.url = v.image_url;`);
lines.push("");

console.log(lines.join("\n"));
